import { Image, SpriteSheet, Audio } from './util';
import { image, sound, music, loadFont, spritesheet } from './util';

/* Images */
const images: Image[] = [
	// Backgrounds
	image('backgrounds/background', 'background'),
	image('backgrounds/bkg_test', 'bkg_test'),
	image('backgrounds/upgrade_page', 'upgrade_page'),
	image('backgrounds/widgets_0', 'widgets_0'),
	image('backgrounds/widgets_1', 'widgets_1'),
	image('backgrounds/widgets_2', 'widgets_2'),
	image('backgrounds/widgets_3', 'widgets_3'),
	image('backgrounds/widgets_4', 'widgets_4'),
	image('backgrounds/1-0', '1-0'),
	image('backgrounds/1-1', '1-1'),
	image('backgrounds/1-2', '1-2'),
	image('backgrounds/1-3', '1-3'),
	image('backgrounds/transition_0', 'transition_0'),
	image('backgrounds/transition_1', 'transition_1'),
	image('backgrounds/transition_2', 'transition_2'),
	image('backgrounds/cutscene/bz_0', 'bz_0'),
	image('backgrounds/cutscene/bz_1', 'bz_1'),
	image('backgrounds/cutscene/bz_2', 'bz_2'),
	image('backgrounds/cutscene/bz_3', 'bz_3'),
	image('backgrounds/cutscene/bz_4', 'bz_4'),
	image('backgrounds/cutscene/bz_5', 'bz_5'),
	image('backgrounds/cutscene/bz_6', 'bz_6'),
	image('backgrounds/cutscene/bz_7', 'bz_7'),
	image('backgrounds/cutscene/bz_8', 'bz_8'),
	image('backgrounds/fr0', 'fr0'),
	image('backgrounds/fr1', 'fr1'),
	image('backgrounds/fr2', 'fr2'),
	image('backgrounds/fr3', 'fr3'),
	image('backgrounds/fr4', 'fr4'),
	image('backgrounds/fr5', 'fr5'),
	image('backgrounds/fr6', 'fr6'),
	image('backgrounds/fr7', 'fr7'),
	image('backgrounds/fr8', 'fr8'),

	image('backgrounds/ds0', 'ds0'),
	image('backgrounds/ds1', 'ds1'),
	image('backgrounds/ds2', 'ds2'),
	image('backgrounds/ds3', 'ds3'),
	image('backgrounds/ds4', 'ds4'),

	image('backgrounds/st0', 'st0'),
	image('backgrounds/st1', 'st1'),
	image('backgrounds/st2', 'st2'),
	image('backgrounds/st3', 'st3'),
	image('backgrounds/st4', 'st4'),

	image('backgrounds/tt1', 'tt1'),
	image('backgrounds/tt2', 'tt2'),
	image('backgrounds/alpha', 'alpha'),
	image('backgrounds/beta', 'beta'),
	image('backgrounds/gamma', 'gamma'),

	image('backgrounds/blank_bkg', 'blank_bkg'),
	image('backgrounds/white_bkg', 'white_bkg'),
	image('backgrounds/black_bkg', 'black_bkg'),
	image('backgrounds/vscreen', 'vscreen'),

	// Characters
	image('characters/player', 'player'),
	image('characters/enemy_1', 'enemy_1'),
	image('characters/enemy_2', 'enemy_2'),
	image('characters/enemy_3', 'enemy_3'),
	image('characters/enemy_4', 'enemy_4'),
	image('characters/blaster_head', 'blaster_head'),
	image('characters/bullet_1', 'bullet_1'),
	image('characters/missile', 'missile'),
	image('characters/blank', 'blank'),
	image('characters/flak', 'flak'),
	image('characters/nuke', 'nuke'),
	image('characters/baguette', 'baguette'),
	image('characters/futbol', 'futbol'),
	image('characters/bigblue', 'bigblue'),
	image('characters/bigblack', 'bigblack'),
	image('characters/medblue', 'medblue'),
	image('characters/medblack', 'medblack'),
	image('characters/tinyblue', 'tinyblue'),
	image('characters/tinyblack', 'tinyblack'),
	image('characters/fish_small', 'fish_small'),
	image('characters/bread_small', 'bread_small'),
	image('characters/hsmall', 'hsmall'),
	image('characters/hbig', 'hbig'),
	image('characters/daybird', 'daybird'),
	image('characters/nightbird', 'nightbird'),
	image('characters/fwhite', 'fwhite'),
	image('characters/fblack', 'fblack'),
	image('characters/fwhitebig', 'fwhitebig'),
	image('characters/fblackbig', 'fblackbig'),
	image('characters/pan', 'pan'),
	image('characters/f1', 'f1'),
	image('characters/f2', 'f2'),
	image('characters/f3', 'f3'),
	image('characters/f4', 'f4'),
	image('characters/f5', 'f5'),
	image('characters/f6', 'f6'),
	image('characters/f7', 'f7'),
	image('characters/f8', 'f8'),
	image('characters/turtle', 'turtle'),
	image('characters/turtle2', 'turtle2'),
	image('characters/trojan', 'trojan'),
	image('characters/curse_rock', 'curse_rock'),
	image('characters/small_curse_rock', 'small_curse_rock'),
	image('characters/rock1', 'rock1'),
	image('characters/rock2', 'rock2'),
	image('characters/ruby', 'ruby'),
	image('characters/emerald', 'emerald'),
	image('characters/diamond', 'diamond'),
	image('characters/snailenemy', 'snailenemy'),
	image('characters/dice_red', 'dice_red'),
	image('characters/mandala_brasil', 'mandala_brasil'),
	image('characters/mandala_french', 'mandala_french'),
	image('characters/purple_bullet', 'purple_bullet'),
	image('characters/small_bullet', 'small_bullet'),
	image('characters/green_bullet', 'green_bullet'),
	image('characters/brasil_laser', 'brasil_laser'),
	image('characters/brasil_laser_origin', 'brasil_laser_origin'),
	image('characters/yellow_laser', 'yellow_laser'),
	image('characters/yellow_laser_origin', 'yellow_laser_origin'),
	image('characters/orange_laser', 'orange_laser'),
	image('characters/orange_laser_origin', 'orange_laser_origin'),
	image('sprites/eiffel', 'eiffel'),
	image('sprites/finalboss_2', 'finalboss_2'),
	image('sprites/enemy_cross', 'enemy_cross'),
	image('sprites/enemy_cross_small', 'enemy_cross_small'),
	image('sprites/heart', 'heart'),

	// Items
	image('items/coin', 'coin'),
	image('items/red', 'red'),
	image('items/blue', 'blue'),
	image('items/gold', 'gold'),
	image('items/rainbow', 'rainbow'),
	image('items/gray', 'gray'),
	image('items/next_scene_button', 'next_scene_button'),

	//
	image('effects/reticle', 'reticle'),
	image('effects/marker', 'marker'),
	image('effects/eiffeltitle', 'eiffeltitle'),
	image('effects/victory', 'victory'),

	// UI
	image('ui/hud', 'hud'),
	image('ui/lives_bar', 'lives_bar'),

	// Titlescreen
	image('titlescreen/sky', 'title_sky'),
	image('titlescreen/background', 'title_background'),
	image('titlescreen/foreground', 'title_foreground'),
	image('titlescreen/character', 'title_character'),
];

/* Spritesheets */
const spritesheets: SpriteSheet[] = [
	spritesheet("sprites/turretbase", "turretbase", 256, 256),
	spritesheet("sprites/gun_1", "gun_1", 256, 256),
	spritesheet("sprites/boosters", "boosters", 256, 512),
	spritesheet("sprites/enemy_5", "enemy_5", 256, 256),
	spritesheet("sprites/finalboss", "finalboss", 512, 860),
	spritesheet("sprites/collider_1", "collider_1", 360, 360),
	spritesheet("sprites/next_button", "next_button", 256, 256),
	spritesheet("sprites/dice_vertical", "dice_vertical", 256, 256),
	spritesheet("sprites/dice_horizontal", "dice_horizontal", 256, 256),
	spritesheet("sprites/dice_cross", "dice_cross", 256, 256),
	spritesheet("sprites/shield", "shield", 512, 860),
	spritesheet("sprites/mine", "mine", 160, 160),
	spritesheet("sprites/teslacopter", "teslacopter", 256, 256),
	spritesheet("sprites/burningbush", "burningbush", 256, 256),
	//spritesheet("sprites/bullet_1", "bullet_1", 128, 128),
	spritesheet("effects/flash", "flash", 128, 128),
	spritesheet("effects/hit_spark", "hit_spark", 128, 128),
	spritesheet("effects/meme_explosion", "meme_explosion", 200, 282),
	spritesheet("effects/explosion_orange", "explosion_orange", 256, 256),
	spritesheet("effects/explosion_tiny", "explosion_tiny", 512, 512),
	spritesheet("effects/bad_fire", "bad_fire", 512, 512),
	spritesheet("effects/blue_sparkle", "blue_sparkle", 256, 256),
	spritesheet("effects/gray_magic", "gray_magic", 128, 128),
	spritesheet("effects/red_magic", "red_magic", 128, 128),
	spritesheet("effects/blue_magic", "blue_magic", 128, 128),
	spritesheet("effects/gold_magic", "gold_magic", 128, 128),
	spritesheet("effects/rainbow_magic", "rainbow_magic", 128, 128),
	spritesheet("sprites/squire", "squire", 270, 270),
	spritesheet("sprites/turret_image", "turret_image", 256, 256),
	
	
];

/* Audios */
const audios: Audio[] = [
	music('title', 'm_main_menu'),
	music('first', 'm_first'),
	music('st1', 'm_st1'),
	music('st2', 'm_st2'),
	music('ba1', 'm_ba'),
	music('final2', 'm_final2'),
	music('final3', 'm_final3'),
	music('hokkai', 'm_boss0'),
	music('bossinit', 'm_boss1'),
	music('m_end', 'm_end'),
	sound('tree/rustle', 't_rustle', 0.5),
	sound('tree/siren', 'siren', 0.8),
	sound('tree/shot_1', 'shot_1', 0.25),
	sound('tree/hit_1', 'hit_1', 0.25),
	sound('tree/turret_dead', 'turret_dead', 0.25),
	sound('tree/dead_1', 'dead_1', 0.25),
	sound('tree/dead_2', 'dead_2', 0.25),
	sound('tree/dead_3', 'dead_3', 0.25),
	sound('tree/dead_4', 'dead_4', 0.25),
	sound('tree/dead_5', 'dead_5', 0.25),
	sound('tree/hit_pierce', 'hit_pierce', 0.25),
	sound('tree/spawn', 'spawn', 0.25),
	sound('tree/machinegun', 'machinegun', 0.25),
	sound('tree/missile_sound', 'missile_sound', 0.25),
	sound('tree/meme_explosion_sound', 'meme_explosion_sound', 0.25),
	sound('tree/crit', 'crit', 0.25),
	sound('tree/bigfire', 'bigfire', 0.25),
	sound('tree/onhit', 'onhit', 0.25),
	sound('tree/scroll', 'scroll', 0.25),
	sound('tree/place', 'place', 0.25),
	sound('tree/turret_hit', 'turret_hit', 0.25),
	sound('tree/escape', 'escape', 0.25),
	sound('tree/big_gun_1', 'big_gun_1', 0.25),
	sound('tree/dice', 'dice', 0.25),
	sound('tree/big_explosion', 'big_explosion', 0.25),
	sound('tree/reflect', 'reflect', 0.25),
	sound('tree/dead_6', 'dead_6', 0.25),
	sound('tree/charge_big', 'charge_big', 0.25),
	sound('tree/laser', 'laser', 0.25),
	sound('tree/cross_dead', 'cross_dead', 0.25),
	sound('tree/bushdeath', 'bushdeath', 0.25),
	sound('tree/alarm', 'alarm', 0.25),
	sound('tree/blaster_spawn', 'blaster_spawn', 0.25),
	sound('tree/blaster_fire', 'blaster_fire', 0.25),
	sound('tree/unf', 'unf', 0.25),
	sound('tree/shadow', 'shadow', 0.25),
	sound('tree/unshadow', 'unshadow', 0.25),
	sound('tree/smash_1', 'smash_1', 0.25),
	sound('tree/warning3', 'warning3', 0.25),
	sound('tree/fshot', 'fshot', 0.25),
	sound('tree/sd', 'sd', 0.25),
	sound('tree/sn', 'sn', 0.25),
	sound('tree/pan', 'pansound', 0.25),
	sound('tree/bigboom', 'bigboom', 0.25),
	sound('tree/slap', 'slap', 0.25),
	sound('tree/lifeup', 'lifeup', 0.25),
	sound('tree/walk', 'walk', 0.25),
	sound('tree/collect', 'eat', 0.25),
	sound('tree/mc_expl1', 'mc_expl1', 0.25),
	sound('tree/mc_expl2', 'mc_expl2', 0.25),
	sound('tree/giantboom', 'giantboom', 0.25),
	sound('tree/thshoot', 'thshoot', 0.25),
	sound('tree/shot-1', 'shot-1', 0.25),
	sound('tree/tspawn', 'tspawn', 0.25),
	sound('tree/breadhit', 'breadhit', 0.25),
];

/* Fonts */
await loadFont('DynaPuff-Medium', 'Game Font');

export {
	images,
	spritesheets,
	audios
};